
(defun inspiration-739689 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-739689
     ((background-color . "#011306")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#D5FF76"))))
     (font-lock-constant-face ((t (:foreground "#2512B1"))))
     (font-lock-builtin-face ((t (:foreground "#87A748"))))
     (font-lock-function-name-face ((t (:foreground "#DDFF3D"))))
     (font-lock-variable-name-face ((t (:foreground "#15FF00"))))
     (font-lock-keyword-face ((t (:foreground "#07FF00"))))
     (font-lock-string-face ((t (:foreground "#52B85E"))))
     (font-lock-doc-string-face ((t (:foreground "#52B85E"))))
     (font-lock-type-face ((t (:foreground "#00F75E"))))
     )))

(provide 'inspiration-739689)