
(defun inspiration-961044 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-961044
     ((background-color . "#000000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#96FC00"))))
     (font-lock-constant-face ((t (:foreground "#B57700"))))
     (font-lock-builtin-face ((t (:foreground "#78AAA3"))))
     (font-lock-function-name-face ((t (:foreground "#C2441D"))))
     (font-lock-variable-name-face ((t (:foreground "#9DA794"))))
     (font-lock-keyword-face ((t (:foreground "#D9A583"))))
     (font-lock-string-face ((t (:foreground "#FFB18B"))))
     (font-lock-doc-string-face ((t (:foreground "#FFB18B"))))
     (font-lock-type-face ((t (:foreground "#B2921A"))))
     )))

(provide 'inspiration-961044)