
(defun color-theme-chocolatier ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-866533
     ((background-color . "#000000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#F0FF5F"))))
     (font-lock-constant-face ((t (:foreground "#FF2612"))))
     (font-lock-builtin-face ((t (:foreground "#FFCDCE"))))
     (font-lock-function-name-face ((t (:foreground "#A43A10"))))
     (font-lock-variable-name-face ((t (:foreground "#6CD675"))))
     (font-lock-keyword-face ((t (:foreground "#B48966"))))
     (font-lock-string-face ((t (:foreground "#8C660C"))))
     (font-lock-doc-string-face ((t (:foreground "#8C660C"))))
     (font-lock-type-face ((t (:foreground "#FF0023"))))
     )))

(provide 'inspiration-866533)
