#!/bin/bash

default_dmg_path="${HOME}/Dropbox/secrets_$(hostname -s).dmg"

stored_secrets_path="${HOME}/Dropbox/.dropbox_secrets_path_$(hostname -s)"

if [ -f "$stored_secrets_path" ]; then
  dmg_path=$(cat "$stored_secrets_path")
fi

if [ ! -f "$dmg_path" ]; then
  # Prompt for dmg_path with default
  read -rp "Enter path to secrets dmg [$default_dmg_path]: " input
  dmg_path=${input:-$default_dmg_path}
  echo "$dmg_path" > "$stored_secrets_path"

  hdiutil create -size 100m -encryption -type UDIF -fs APFS -volname secrets "$dmg_path"
fi

# Mount the dmg if not mounted
if ! mount | grep -q "$dmg_path"; then
  echo "Mounting secrets dmg, you probably want to check the save password box..."
  open "$dmg_path"
fi

echo "Now you probably want to add the dmg to your login items..."

open -R "$dmg_path"

# Open my login items preferences in macOS
open "x-apple.systempreferences:com.apple.LoginItems-Settings.extension"

echo "You might want to move stuff to /Volumes/secrets now"
