# This file generates the correct .gitignore file for the common files, based on HEAD for your installed
# repo. Just run it, and it will print what should go into the .gitignore file.

# Sample Command: ruby ~/.common_files/generate_gitignore.rb

require 'rubygems'
require 'grit'
include Grit

exceptions_to_the_exception = { 
  ".emacs.d" => ["semantic.cache"],
  ".common_files" => ["*svn", ".last_checked_date", ".out_of_date_last_notified_date", ".out_of_date_notification_message", "cf.conf"]
}

def common_files_repo
  Repo.new("~")
end

def find_directories_from_git_tree(tree)
  # this abuses the fact that directories don't have the mime_type function defined
  tree.contents.select {|x| !(x.mime_type rescue nil) }
end 

def directories_in_the_common_files
  find_directories_from_git_tree(common_files_repo.commits.first.tree)
end

def ignore_lines_for_a_directory(git_dir)
  <<-eos
!#{git_dir.name}
!#{git_dir.name}/**
  eos
end

# Disclaimer
def disclaimer
  <<-eos
# This file is auto-generated by the .common_files/generate_gitignore.rb file. If you edit it by hand, it will
# be overwritten the next time that script is run. You should just edit the script to be correct.

  eos
end 



######
# The Real Program
#####


File.open(".gitignore", "w+") do |f|
  f.puts disclaimer
  
  #Ignore Everything
  f.puts "*"

  # Except This Stuff
  f.puts "!.gitignore"
  directories_in_the_common_files.each do |dir|
    f.puts ignore_lines_for_a_directory(dir)
  end
end

directories_in_the_common_files.each do |dir|
  File.open("#{dir.name}/.gitignore","w+") do |f|
    f.puts disclaimer
    f.puts "!**"
    ["*svn", "*~"].each {|exclusion| f.puts exclusion }
    f.puts exceptions_to_the_exception[dir.name].join("\n") if exceptions_to_the_exception[dir.name]
  end
end
