#!/bin/bash

# SSH with host name and IP address in background (only in iTerm.app)

# First, check to see if we have the correct terminal!
if [ "$(tty)" == 'not a tty' ] || [ "$TERM_PROGRAM" != "iTerm.app" ] ; then
  /usr/bin/ssh "$@"
  exit $?
fi

function __calculate_iterm_window_dimensions {
  local size=( $(arch -i386 osascript -e "tell application \"iTerm\"
    get bounds of window 1
  end tell" | tr ',' ' ') )

  local x1=${size[0]} y1=${size[1]} x2=${size[2]} y2=${size[3]}
  # 15px - scrollbar width
  local w=$(( $x2 - $x1 - 15 ))
  # 44px - titlebar + tabs height
  local h=$(( $y2 - $y1 - 44))
  echo "${w}x${h}"
}

# Console dimensions
DIMENSIONS=$(__calculate_iterm_window_dimensions)

BG_COLOR="#000000"        # Background color
NORMAL_FG_COLOR="#206620" # FG for normal user
DEPLOY_FG_COLOR="#2020CC" # FG for deploy user
ROOT_FG_COLOR="#CC2020"   # FG for root user
GRAVITY="NorthEast"       # Text gravity (NorthWest, North, NorthEast,
                          # West, Center, East, SouthWest, South, SouthEast)
OFFSET1="20,0"           # Text offset (host name)
OFFSET2="20,60"           # Text offset (ip address)
OFFSET3="20,86"          # Text offset (username)
FONT_SIZE="60"            # Font size in points
FONT_STYLE="Normal"       # Font style (Any, Italic, Normal, Oblique)
# Font path
FONT="/Library/Fonts/Futura.ttc"

USERNAME=`echo $@ | sed 's/.* \(.*\)$/\1/' | sed "s/@.*//"`
HOSTNAME=`echo $@ | sed 's/.* \(.*\)$/\1/' | sed "s/.*@//"`

if [ $USERNAME == "root" ] ; then
  FG_COLOR=$ROOT_FG_COLOR
elif [ $USERNAME == "deploy" ] ; then
  FG_COLOR=$DEPLOY_FG_COLOR
else
  FG_COLOR=$NORMAL_FG_COLOR
fi

output=`dscacheutil -q host -a name $HOSTNAME`
RESOLVED_HOSTNAME=`echo -e "$output"|grep '^name:'|awk '{print $2}'`
RESOLVED_IP=`echo -e "$output"|grep '^ip_address:'|awk '{print $2}'`

function set_bg {
  local tty=$(tty)
  arch -i386 osascript -e "
    tell application \"iTerm\"
      repeat with theTerminal in terminals
        tell theTerminal
          try
            tell session id \"$tty\"
              set background image path to \"$1\"
            end tell
          on error errmesg number errn
          end try
        end tell
      end repeat
    end tell"
}

on_exit () {
  if [ ! -f /tmp/iTermBG.empty.png ]; then
    convert -size "$DIMENSIONS" xc:"$BG_COLOR" "/tmp/iTermBG.empty.png"
  fi
  set_bg "/tmp/iTermBG.empty.png"
  rm "/tmp/iTermBG.$$.png"
}
trap on_exit EXIT

convert \
  -size "$DIMENSIONS" xc:"$BG_COLOR" -gravity "$GRAVITY" -fill "$FG_COLOR" \
  -font "$FONT" -style "$FONT_STYLE" -pointsize "$FONT_SIZE" -antialias \
  -draw "text $OFFSET1 '${RESOLVED_HOSTNAME:-$HOSTNAME}'" \
  -pointsize 30 -draw "text $OFFSET2 '${RESOLVED_IP:-}'" \
  -pointsize 30 -draw "text $OFFSET3 '${USERNAME:-}'" \
  "/tmp/iTermBG.$$.png"
set_bg "/tmp/iTermBG.$$.png"

/usr/bin/ssh "$@"
