#!/bin/bash
set -e

INSTALL_SCRIPTS_PATH="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)"
source "$INSTALL_SCRIPTS_PATH/helper_functions"

install_app_configurations() {
  setup_echo "SET UP YER APPS (hit enter when done)"
  read set_up_apps
  #flowdock

  #launchbar

  #divvy
  # maximize window

  # Setup chrome work and chrome personal
  # transfer tabs using history - "tabs from other devices"
  # verify 1password works

  # anki
  # word
  # excel
  # setup AWS credentials  
}


############################################
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_app_configurations
fi
