#!/bin/bash
set -e

INSTALL_SCRIPTS_PATH="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)"
source "$INSTALL_SCRIPTS_PATH/helper_functions"

install_global_ruby() {
  setup_echo "Install a recent ruby and make it the default instead of system ruby"
  eval "$(rbenv init -)"
  rbenv install 2.6.3
  eval "$(rbenv global 2.6.3)"
  #rbenv global 2.6.3 #TODO: this doesn't work because of environment bullshit
}

############################################
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_global_ruby
fi
