# Basic stuff that helps with machine setup, dotfiles dependencies, first so
# things are usable more quickly
brew 'terminal-notifier'
brew 'stow'
brew 'rclone'
brew 'git-delta'
brew 'less'
brew 'bat'
brew 'sheldon'
brew 'fzf'
brew 'ripgrep'
brew 'the_silver_searcher'
brew 'watch'
brew 'wget'
brew 'gnupg2'
brew 'diff-so-fancy'
brew 'rbenv-default-gems'
cask 'iterm2'
cask 'google-chrome'
cask 'atom'
cask 'flowdock'
cask 'firefox'
cask 'launchbar'
cask 'divvy'
